version: '3.4'

services:
  yourchores.web:
    image: ${DOCKER_REGISTRY-}no1225/yourchoresweb    
    container_name: yourchoresweb
    build:
      context: .
      dockerfile: Dockerfile
   
  sslmanager:
    image: linuxserver/letsencrypt
    container_name: sslmanager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=yourchores.me
      - SUBDOMAINS=www,
      - VALIDATION=http
      - STAGING=true #optional
    volumes:
      - ./nginx/config:/config
      - ./nginx/nginx.conf:/config/nginx/site-confs/default
      - ./nginx/ssl.conf:/config/nginx/ssl.conf
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped